name: Build

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Java setup
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 8
          cache: gradle

      - name: Increase Gradle timeout
        run: echo "systemProp.http.socketTimeout=60000" >> ~/.gradle/gradle.properties

      - name: Build
        run: |
          chmod +x ./gradlew
          ./gradlew setupCiWorkspace --no-daemon
          ./gradlew clean --no-daemon
          ./gradlew build --no-daemon --refresh-dependencies

      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Haru
          path: build/libs/Haru.jar
