name: Build

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Java setup
        uses: actions/setup-java@v2
        with:
          distribution: "adopt"
          java-version: 8
          cache: "gradle"
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      
      - name: Build
        run: ./gradlew clean build
        
      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Haru
          path: build/libs/
